version: '3.9'

services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py csu && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    environment:
      - DEBUG=True
      - POSTGRES_HOST=db
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:

volumes:
  postgres_data:
    driver: local
  static_volume:
    driver: local
